MODULE HIP_PROFILING

INTERFACE
  SUBROUTINE ROCTXMARKA(message) BIND(c,name="roctxMarkA")
    USE ISO_C_BINDING, ONLY : C_CHAR
    IMPLICIT NONE
    CHARACTER(C_CHAR) :: message(*)
  END SUBROUTINE ROCTXMARKA

  FUNCTION ROCTXRANGEPUSHA(message) BIND(c,name="roctxRangePushA")
    USE ISO_C_BINDING, ONLY : C_INT,C_CHAR
    IMPLICIT NONE
    INTEGER(C_INT) :: roctxRangePushA
    CHARACTER(C_CHAR) :: message(*)
  END FUNCTION ROCTXRANGEPUSHA

  SUBROUTINE ROCTXRANGEPOP() BIND(c,name="roctxRangePop")
    IMPLICIT NONE
  END SUBROUTINE ROCTXRANGEPOP
END INTERFACE

END MODULE HIP_PROFILING
